graph LR
    subgraph 赛事端→社团端 Fc-10
    CH1-2[CH-1-2 排行榜] -- 社团名点击 --> CC4[CC-4 社团主页]
    CH1-3[CH-1-3 作品列表] -- 社团标识点击 --> CC4
    CH2[CH-2 作品详情] -- 社团标识点击 --> CC4
    end

    subgraph 社团端→赛事端 Fc-09
    CC5[CC-5 专属花絮活动] -- 顶部入口① --> CH1[CH-1 赛事主页]
    CC5 -- 顶部入口② --> CH1-3F[CH-1-3 本社团作品筛选态]
    end
